BranchTaken/Hemlock

src/stdlib/array.hli

For most Array functions, environment mutation is both unnecessary and
undesirable.  The plain iteration functions are an exception, since they have
no way of getting work done besides mutating the environment.

Fix Array.iter[i]2 signatures to allow environment mutation.

---

bootstrap/bin/hlc.ml

Fix hlc.ml to fully adopt uint-to-usize renaming and related API changes.  Also
clean up the code to match its current minimal intent of verifying that an
executable can compile and execute using the bootstrap library code.
This regression was introduced by dfdaa2384213394ea3818e717c0f9e5d3eacd85d
(Rename uint/int to usize/isize, and make usize the default integer type.).

Fix hlc compilation.

---

.github/workflows/test.yml

resolve #35 
The initial version includes a caching mechanism. It caches everything in the ~/.opam directory after the first successful run. The key is hashed based on the OS name and the contents of any *.opam file in our repo. If a new PR is opened and no *.opam file changes were made in the PR, the CI reloads the cached data in ~/.opam and avoids building it from scratch.
Note that there are two sections of the CI that benefit from the caching.
- 'opam' - This section always runs, but if we successfully reloaded from cache, the underlying action's download manager is smart enough to skip downloading cached dependencies. This action does some other useful things for us, like setting up our opam environment.
- 'init' - Here we would call opam init on a cache miss, but on a hit, all the …

Create github action to run tests on pull request

---

bootstrap/src/hash.c

getentropy() on macOS requires the sys/random.h header; include it.
Add missing 'return' keyword.

Fix warnings for macOS build.

---

.github/scripts/check_ocp_indent.py
.github/workflows/test.yml

This script checks that lines modified in a PR (compared to
origin/master) are indented as suggested by ocp-indent. If ocp-indent
would have done anything different with modified lines in this PR, the
check fails and prints suggested changes from ocp-indent.
ref #27

Add ocp-indent checker for pull-requests.

---

.github/scripts/check_ocp_indent.py
.ocp-indent

Fixes these two bad behaviors discovered in check_ocp_indent.py.
1. Hunks that were entirely deleted were incorrectly detected as a
single line addition by the script's hunk header pattern match. This
caused weird indentation in places where blocks of code were deleted.
2. The script did not have an ocp-indend config that matched developer
configurations. The addition of the .ocp-indent file will cause
ocp-indent to use the correct configuration if it is run anywhere within
this repo. It is not in REPO_ROOT/boostrap since it is also relevant for
scripts in REPO_ROOT/.github/scripts.

Fix bug in check_ocp_indent.py

---

bootstrap/src/basis/array.ml

This function was apparently never used before.

of_list_rev

---

bootstrap/src/basis/map.ml
bootstrap/src/basis/map_intf.ml
bootstrap/src/basis/ordmap.ml
bootstrap/src/basis/ordset.ml
bootstrap/src/basis/set.ml
bootstrap/src/basis/set_intf.ml

These functions aren't overly important for maps, but they should definitely be provided for sets.

Implement {Ordmap,Map,Ordset,Set}.{subset,disjoint} .

---

bootstrap/src/basis/map.ml
bootstrap/src/basis/map_intf.ml
bootstrap/src/basis/ordmap.ml
bootstrap/src/basis/ordset.ml
bootstrap/src/basis/set.ml
bootstrap/src/basis/set_intf.ml

I didn't plan on adding these, but discovered while writing 'remove' benchmarks that there was no straightforward way to choose an arbitrary element of an unordered  map/set.  For ordered maps/sets we have `nth`, but the best we can do for unordered maps/sets absent `choose` is to `fold_until` and terminate after the first iteration.

Add choose[_hlt] to maps and sets.

---

bootstrap/src/basis/ordmap.ml

One might think that the compiler would favor the more complicated old version because it reduces duplicated conditional logic, but the resulting tuple allocation overwhelms the savings.  Let's favor the simple code, and assume that the Hemlock compiler will eventually merge the branches.

Simplify node_init for clarity and performance (avoids tuple allocation).

---

bootstrap/src/basis/array.ml

This simplification allows proper parametric mutability in a straightforward
Hemlock translation.

Refactor Array.Array_join .

---

bootstrap/src/basis/bytes.ml
bootstrap/src/basis/bytes.mli
bootstrap/src/basis/text.ml

Add Excerpt.Cursor.t which is a flat wrapper around Bytes.Cursor.t to remove
duplicate references to the containing excerpt in Text.Cursor.t .

Reduce size of Text.Cursor.t .

---

.docker-compose.yml
.dockerfile
README.md

This enables us to manually set the target platform for our image using the HEMLOCK_PLATFORM
environment variable. There are less-verbose ways of plumbing the target platform through, such as
using the `platform: ` key in docker-compose.yml. However, by doing it in here, the default value
for HEMLOCK_PLATFORM is set equal to the docker buildx BUILDPLATFORM environment variable, which
matches the builder's host platform. That means that in the cases where we connect a remote builder
(AWS Graviton, for instance), the default target platform will match that of the builder and not of
the local host where the CLI commands are invoked.

Enable multi-platform Docker build.

---

.github/scripts/check_ocp_indent.py
.github/workflows/test.yml
README.md

Default branch naming inconsistency among repos is starting to chafe.
CI is going to fail for this commit, since the branch rename cannot be done as part of the commit itself.

Rename 'master' branch to 'main'.

---

doc/design/execution_stack.md
doc/design/memory.md
doc/design/work_stealing.md

There are still some small TODO items for this doc, but the contents and organization are generally done.

Add execution stack design doc.

---

doc/design/memory.md

I was perusing design notes to remind myself of wilderness reset optimization constraints, and discovered that one of the constraints didn't make it into the design doc.

Document that forcing lazy suspensions can prevent wilderness reset.

---

bootstrap/.merlin

Merlin configuration has been auto-generated by dune for several releases, and
the presence of a .merlin file prevents proper function of ocaml-lsp.

Remove .merlin file.

---

bootstrap/src/basis/file.c

Fixes #129
Manual test with the following at the command line.
```
dune exec hmc /home/hemlock/Hemlock/src/Basis/Array.hm
```
Before the change, this results in the output
```
Halt: File.of_path error: No such file or directory
```
Array.hm clearly exists at this location in the Hemlock image, so this was a bug.
After the changes in this PR, the result is that the test print the expected `hmc` output.
`deflate_bytes()` is only used to prepare a `Bytes.t` to be used with a system call. A `Bytes.t` in
memory actually uses 32 bits per byte, so a `Bytes.t` with the value `"path"` might look like
```
? ? ? p ? ? ? a ? ? ? t ? ? ? h
```
After `deflate_bytes()`, it looks like
```
p a t h ? ? ? a ? ? ? t ? ? ? h
```
To be safe with a system call, it needs to be null-terminated.
```
p a t h\0 ? ? …
```

Fix missing '\0' termination in deflate_bytes().

---

doc/design/memory.md

The corresponding figure correctly depicts seven regions.

Update verbiage to refer to seven (not nine) regions per actor.

---

Dockerfile
docker-compose.yml

This makes so that `docker buildx build .` can take advantage of the same default settings as `docker compose build`.

Move default docker build args to Dockerfile.

---

Dockerfile

Docker images now include the `ubuntu` user, which conflicts with the typical uid/gid 1000/1000, and therefore thwarts bind mounts. Rename the user.

Rename `ubuntu` user to `hemlock`

---

.github/workflows/test.yml
Dockerfile
docker-compose.yml

`io_uring_enter`, `io_uring_register`, and `io_uring_setup` were taken out of the Docker default seccomp profile (see
https://github.com/moby/moby/commit/891241e7e74d4aae6de5f6125574eb994f25e169). This caused our tests to fail with `permission denied` when calling any of those system calls during `docker compose build tested`.
This commit changes our seccomp profile to unconfined and runs our containers as privileged. Also, since images can only be built with the default profile, we can no longer run our tests during image build time. They are now run as a container command.

Fixes io_uring permission error in Docker.

---

bootstrap/src/basis/common.h
bootstrap/src/basis/executor.c
bootstrap/src/basis/executor.h
bootstrap/src/basis/file.c
bootstrap/src/basis/file.ml
bootstrap/src/basis/ioring.c
bootstrap/src/basis/ioring.h
bootstrap/test/basis/file/test_file_full_sq.ml
bootstrap/test/basis/file/test_file_open.ml

This makes all c-layer methods more consistent with the rest of the Hemlock project. Functions and macros previously prefixed with `hm_` or `HM_` are now prefixed with `hemlock_` or `HEMLOCK_` respectively.

Rename `File` c-layer methods.
